export type ToolType =
	| 'GitHub'
	| 'GitLab'
	| 'Bitbucket'
	| 'Visual Studio Code'
	| 'WebStorm'
	| 'Insomnia'
	| 'Postman'
	| 'Jira'
	| 'ClickUp'
	| 'Slack'
	| 'Trello'
	| 'Adobe Photoshop'
	| 'Adobe Illustrator'
	| 'Affinity Designer'
	| 'Affinity Photo'
	| 'Adobe XD'
	| 'Figma'
	| 'Canva'
	| 'Netlify'
	| 'Vercel';
